services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=coindeed
      - POSTGRES_USER=coindeed
      - POSTGRES_DB=coindeed
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - coindeed-net

networks:
  coindeed-net:
    driver: bridge
